print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/florianpeinsold/Documents/FH/PRO4/pro4_en/Base2/Assets/Objects/All Assets/Bridge_Start.mb"`)
{		
	file -o "/Users/florianpeinsold/Documents/FH/PRO4/pro4_en/Base2/Assets/Objects/All Assets/Bridge_Start.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/florianpeinsold/Documents/FH/PRO4/pro4_en/Base2/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/florianpeinsold/Documents/FH/PRO4/pro4_en/Base2/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/florianpeinsold/Documents/FH/PRO4/pro4_en/Base2/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
